#!/bin/bash
echo "🚀 Pocket Agent Development"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📂 Current directory: $(pwd)"
echo "🌿 Current branch: $(git branch --show-current)"
echo "📦 Node version: $(node -v)"
echo ""
echo "Quick commands:"
echo "  npm run dev       → Start development mode"
echo "  npm run build     → Build for production"
echo "  npm run package   → Create .app bundle"
echo ""
echo "Update from upstream:"
echo "  ./scripts/update-from-upstream.sh"
echo ""
echo "📖 Read: SETUP_COMPLETE.md for full guide"
echo ""
